## Model Training

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [2]:
df = pd.read_csv('data/cleaned_career_dataset.csv')
df.head()

,experience_years,target_career,aws,azure,business,c++,cloud computing,content writing,css,cybersecurity,...,interests_data,interests_design,interests_marketing,interests_security,interests_web development,certification_Azure Fundamentals,certification_Coursera ML,certification_Google Data Analytics,certification_No Certification,certification_Udemy Web Dev
0,5,6,0,0,1,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,8,0,0,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,4,4,0,0,0,0,0,0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,8,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
4,1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0

In [3]:
X = df.drop('target_career', axis=1)
y = df['target_career']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

models = {
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'KNN': KNeighborsClassifier(),
    'SVM': SVC(probability=True),
    'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
}

In [8]:
def evaluate_model(y_test, y_pred):
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1_scr = f1_score(y_test, y_pred, average='weighted')
    cm = confusion_matrix(y_test, y_pred)
    return accuracy, precision, recall, f1_scr, cm

In [9]:
model_list = []
accuracy_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluate Train and Test dataset
    model_train_acc, model_train_precision, model_train_recall, model_train_f1, model_train_cm = evaluate_model(y_train, y_train_pred)
    model_test_acc, model_test_precision, model_test_recall, model_test_f1, model_test_cm = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print("Model Performance on Train Dataset:")
    print(f"Accuracy: {model_train_acc}")
    print(f"Precision: {model_train_precision}")
    print(f"Recall: {model_train_recall}")
    print(f"F1-Score: {model_train_f1}")
    print("Confusion Matrix:")
    print(model_train_cm)

    print('-'*50)

    print("\nModel Performance on Test Dataset:")
    print(f"Accuracy: {model_test_acc}")
    print(f"Precision: {model_test_precision}")
    print(f"Recall: {model_test_recall}")
    print(f"F1-Score: {model_test_f1}")
    print("Confusion Matrix:")
    print(model_test_cm)

    accuracy_list.append(model_test_acc)
    print('='*50)
    print('\n')

Logistic Regression
Model Performance on Train Dataset:
Accuracy: 0.9634666666666667
Precision: 0.9639682066373791
Recall: 0.9634666666666667
F1-Score: 0.9635073144041336
Confusion Matrix:
[[809   0   0   0   0   0   0   0  16]
 [  0 767   0   5   0  34   0   0   0]
 [  0   0 783   0   0   0   0   0   0]
 [  0  22   0 842   0  71   0   0   0]
 [  0   0   0   0 840   0   0   0   0]
 [  0  59   0  32   0 756   0   0   0]
 [  0   0   0   0   0   0 838   0   0]
 [  0   0   0   0   0   0   0 824   0]
 [ 35   0   0   0   0   0   0   0 767]]
--------------------------------------------------

Model Performance on Test Dataset:
Accuracy: 0.9536
Precision: 0.9543589116571946
Recall: 0.9536
F1-Score: 0.9537435607927444
Confusion Matrix:
[[240   0   0   0   0   0   0   0   3]
 [  0 268   0   6   0  19   0   0   0]
 [  0   0 281   0   0   0   0   0   0]
 [  0   4   0 243   0  32   0   0   0]
 [  0   0   0   0 271   0   0   0   0]
 [  0  32   0  10   0 231   0   0   0]
 [  0   0   0   0   0   0 287   0   0]
 [  0   0   0   0   0   0   0 295   0]
 [ 10   0   0   0   0   0   0   0 268]]
==================================================


Decision Tree
Model Performance on Train Dataset:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-Score: 1.0
Confusion Matrix:
[[825   0   0   0   0   0   0   0   0]
 [  0 806   0   0   0   0   0   0   0]
 [  0   0 783   0   0   0   0   0   0]
 [  0   0   0 935   0   0   0   0   0]
 [  0   0   0   0 840   0   0   0   0]
 [  0   0   0   0   0 847   0   0   0]
 [  0   0   0   0   0   0 838   0   0]
 [  0   0   0   0   0   0   0 824   0]
 [  0   0   0   0   0   0   0   0 802]]
--------------------------------------------------

Model Performance on Test Dataset:
Accuracy: 0.934
Precision: 0.9345418095578815
Recall: 0.934
F1-Score: 0.9340732671942331
Confusion Matrix:
[[237   0   0   0   0   0   0   0   6]
 [  0 246   0  17   0  30   0   0   0]
 [  0   0 281   0   0   0   0   0   0]
 [  0   9   0 241   0  29   0   0   0]
 [  0   0   0   0 271   0   0   0   0]
 [  0  27   0  27   0 219   0   0   0]
 [  0   0   0   0   0   0 287   0   0]
 [  0   0   0   0   0   0   0 295   0]
 [ 20   0   0   0   0   0   0   0 258]]
==================================================


Random Forest
Model Performance on Train Dataset:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-Score: 1.0
Confusion Matrix:
[[825   0   0   0   0   0   0   0   0]
 [  0 806   0   0   0   0   0   0   0]
 [  0   0 783   0   0   0   0   0   0]
 [  0   0   0 935   0   0   0   0   0]
 [  0   0   0   0 840   0   0   0   0]
 [  0   0   0   0   0 847   0   0   0]
 [  0   0   0   0   0   0 838   0   0]
 [  0   0   0   0   0   0   0 824   0]
 [  0   0   0   0   0   0   0   0 802]]
--------------------------------------------------

Model Performance on Test Dataset:
Accuracy: 0.952
Precision: 0.952417653941266
Recall: 0.952
F1-Score: 0.9521080515384818
Confusion Matrix:
[[238   0   0   0   0   0   0   0   5]
 [  0 264   0   5   0  24   0   0   0]
 [  0   0 281   0   0   0   0   0   0]
 [  0   4   0 250   0  25   0   0   0]
 [  0   0   0   0 271   0   0   0   0]
 [  0  28   0  15   0 230   0   0   0]
 [  0   0   0   0   0   0 287   0   0]
 [  0   0   0   0   0   0   0 295   0]
 [ 14   0   0   0   0   0   0   0 264]]
==================================================


Gradient Boosting
Model Performance on Train Dataset:
Accuracy: 0.9736
Precision: 0.9738254341841663
Recall: 0.9736
F1-Score: 0.9736143788950605
Confusion Matrix:
[[813   0   0   0   0   0   0   0  12]
 [  0 777   0   3   0  26   0   0   0]
 [  0   0 783   0   0   0   0   0   0]
 [  0  19   0 864   0  52   0   0   0]
 [  0   0   0   0 840   0   0   0   0]
 [  0  42   0  28   0 777   0   0   0]
 [  0   0   0   0   0   0 838   0   0]
 [  0   0   0   0   0   0   0 824   0]
 [ 16   0   0   0   0   0   0   0 786]]
--------------------------------------------------

Model Performance on Test Dataset:
Accuracy: 0.95
Precision: 0.950656712688728
Recall: 0.95
F1-Score: 0.9501804536552955
Confusion Matrix:
[[238   0   0   0   0   0   0   0   5]
 [  0 264   0   4   0  25   0   0   0]
 [  0   0 281   0   0   0   0   0   0]
 [  0   3   0 246   0  30   0   0   0]
 [  0   0   0   0 271   0   0   0   0]
 [  0  32   0  14   0 227   0   0   0]
 [  0   0   0   0   0   0 287   0   0]
 [  0   0   0   0   0   0   0 295   0]
 [ 12   0   0   0   0   0   0   0 266]]
==================================================

e:\Kaushal AI\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\Kaushal AI\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

AdaBoost
Model Performance on Train Dataset:
Accuracy: 0.5406666666666666
Precision: 0.4042600887700536
Recall: 0.5406666666666666
F1-Score: 0.4378153725864975
Confusion Matrix:
[[  0   0   0   0   0   0   0   0 825]
 [  0 806   0   0   0   0   0   0   0]
 [  0   0 783   0   0   0   0   0   0]
 [  0 935   0   0   0   0   0   0   0]
 [  0   0   0   0 840   0   0   0   0]
 [  0 847   0   0   0   0   0   0   0]
 [  0 838   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 824   0]
 [  0   0   0   0   0   0   0   0 802]]
--------------------------------------------------

Model Performance on Test Dataset:
Accuracy: 0.5672
Precision: 0.4284704604491228
Recall: 0.5672
F1-Score: 0.46437665573194564
Confusion Matrix:
[[  0   0   0   0   0   0   0   0 243]
 [  0 293   0   0   0   0   0   0   0]
 [  0   0 281   0   0   0   0   0   0]
 [  0 279   0   0   0   0   0   0   0]
 [  0   0   0   0 271   0   0   0   0]
 [  0 273   0   0   0   0   0   0   0]
 [  0 287   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 295   0]
 [  0   0   0   0   0   0   0   0 278]]
==================================================


KNN
Model Performance on Train Dataset:
Accuracy: 0.9437333333333333
Precision: 0.9449659255169746
Recall: 0.9437333333333333
F1-Score: 0.9435598202763051
Confusion Matrix:
[[802   5   1   0   1   1   0   0  15]
 [  2 765   1   6   3  24   0   5   0]
 [  0   4 778   1   0   0   0   0   0]
 [ 21  37   5 827   2  37   1   3   2]
 [  0   8   1   2 824   3   0   2   0]
 [  6  67   5  57   6 699   1   6   0]
 [  1   6   1   1   1   3 824   1   0]
 [  0   3   0   0   0   2   0 819   0]
 [ 45  11   0   1   1   3   0   1 740]]
--------------------------------------------------

Model Performance on Test Dataset:
Accuracy: 0.9016
Precision: 0.9033425772811421
Recall: 0.9016
F1-Score: 0.9011657662270892
Confusion Matrix:
[[232   2   0   1   0   0   0   1   7]
 [  3 255   6   6   1  18   0   2   2]
 [  0   5 275   1   0   0   0   0   0]
 [  4  17   5 220   0  31   0   1   1]
 [  0   3   1   3 264   0   0   0   0]
 [  4  45   7  20   3 191   2   0   1]
 [  1   4   0   2   0   1 278   1   0]
 [  1   3   0   0   0   1   0 290   0]
 [ 18   6   0   2   0   1   2   0 249]]
==================================================


SVM
Model Performance on Train Dataset:
Accuracy: 0.9654666666666667
Precision: 0.9658775692248257
Recall: 0.9654666666666667
F1-Score: 0.9655082272138192
Confusion Matrix:
[[811   0   0   0   0   0   0   0  14]
 [  0 766   0   3   0  37   0   0   0]
 [  0   0 783   0   0   0   0   0   0]
 [  0  23   0 848   0  64   0   0   0]
 [  0   0   0   0 840   0   0   0   0]
 [  0  49   0  35   0 763   0   0   0]
 [  0   0   0   0   0   0 838   0   0]
 [  0   0   0   0   0   0   0 824   0]
 [ 34   0   0   0   0   0   0   0 768]]
--------------------------------------------------

Model Performance on Test Dataset:
Accuracy: 0.9516
Precision: 0.9523079259025325
Recall: 0.9516
F1-Score: 0.9518150682966184
Confusion Matrix:
[[241   0   0   0   0   0   0   0   2]
 [  0 259   0   6   0  28   0   0   0]
 [  0   0 281   0   0   0   0   0   0]
 [  0   3   0 247   0  29   0   0   0]
 [  0   0   0   0 271   0   0   0   0]
 [  0  26   0  17   0 230   0   0   0]
 [  0   0   0   0   0   0 287   0   0]
 [  0   0   0   0   0   0   0 295   0]
 [ 10   0   0   0   0   0   0   0 268]]
==================================================

e:\Kaushal AI\venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [15:41:46] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBoost
Model Performance on Train Dataset:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-Score: 1.0
Confusion Matrix:
[[825   0   0   0   0   0   0   0   0]
 [  0 806   0   0   0   0   0   0   0]
 [  0   0 783   0   0   0   0   0   0]
 [  0   0   0 935   0   0   0   0   0]
 [  0   0   0   0 840   0   0   0   0]
 [  0   0   0   0   0 847   0   0   0]
 [  0   0   0   0   0   0 838   0   0]
 [  0   0   0   0   0   0   0 824   0]
 [  0   0   0   0   0   0   0   0 802]]
--------------------------------------------------

Model Performance on Test Dataset:
Accuracy: 0.9452
Precision: 0.9456531043533569
Recall: 0.9452
F1-Score: 0.9453635835751882
Confusion Matrix:
[[233   0   0   0   0   0   0   0  10]
 [  0 256   0   7   0  30   0   0   0]
 [  0   0 281   0   0   0   0   0   0]
 [  0   7   0 246   0  26   0   0   0]
 [  0   0   0   0 271   0   0   0   0]
 [  0  30   0  16   0 227   0   0   0]
 [  0   0   0   0   0   0 287   0   0]
 [  0   0   0   0   0   0   0 295   0]
 [ 11   0   0   0   0   0   0   0 267]]
==================================================

In [10]:
accuracy_df = pd.DataFrame(list(zip(model_list, accuracy_list)), columns=['Model', 'Accuracy Score']).sort_values(by='Accuracy Score', ascending=False)

In [11]:
accuracy_df

                 Model  Accuracy Score
0  Logistic Regression          0.9536
2        Random Forest          0.9520
6                  SVM          0.9516
3    Gradient Boosting          0.9500
7              XGBoost          0.9452
1        Decision Tree          0.9340
5                  KNN          0.9016
4             AdaBoost          0.5672